//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally's Zone
//

import Foundation
import RxSwift

class VFUK___VARIABLE_productName:identifier___Dispatcher: VFUKBaseDispatcher, VFUK___VARIABLE_productName:identifier___DispatcherProtocol {
	func get___VARIABLE_productName:identifier___(cachePolicy: VFUKCachingPolicy & VFUKCachingPolicyProtocol, requestFactory: VFUKBaseRequestFactory, msisdn: String) -> Observable<Result<VFUK___VARIABLE_productName:identifier___Model>> {
		return self.getObservable(cachePolicy: cachePolicy, requestFactory: requestFactory, msisdn: msisdn)
	}
}
