//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally's Zone
//

import Foundation

class VFUK___VARIABLE_productName:identifier___Model: VFUKBaseResponseProtocol {
    let status: VFUKStatusModel?
    
    enum CodingKeys: String, CodingKey {
        case status
    }

    required init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        status = try values.decodeIfPresent(VFUKStatusModel.self, forKey: .status)
    }
}
