//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally's Zone
//

import Foundation
import RxSwift
import RxCocoa

class VFUK___VARIABLE_productName:identifier___ViewModel: VFUKBaseViewModel, VFUK___VARIABLE_productName:identifier___ViewModelProtocol {

    /// The interactor containing the business logic
    private let interactor: VFUK___VARIABLE_productName:identifier___InteractorProtocol

    /// Creates and returns a new ViewModel
	init(interactor: VFUK___VARIABLE_productName:identifier___InteractorProtocol) {
		self.interactor = interactor
        super.init()
		self.configureBinding()
    }

    /// Setup the viewModel and configures the binding to the interactor
    func configureBinding() {
    }
}
