//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally's Zone
//

import Foundation
import RxCocoa
import RxSwift

protocol VFUK___VARIABLE_productName:identifier___ViewControllerProtocol: VFUKBaseViewControllerProtocol {
	func initialize(viewModel: VFUK___VARIABLE_productName:identifier___ViewModelProtocol)
}

protocol VFUK___VARIABLE_productName:identifier___ViewModelProtocol: VFUKBaseViewModelProtocol {
}

protocol VFUK___VARIABLE_productName:identifier___InteractorProtocol: VFUKBaseInteractorProtocol {
}

protocol VFUK___VARIABLE_productName:identifier___DispatcherProtocol: VFUKBaseDispatcherProtocol {
}